#!/bin/bash
# @COPYRIGHT@

WIKITESTS="/usr/share/nlw/wikitests"

echo SETTING TIME
source $WIKITESTS/set-time

echo INSTALLING wikitest_files
if [ ! -e /opt/wikitest_files ]; then
    sudo mkdir /opt/wikitest_files
fi
sudo unzip $WIKITESTS//wikitestfiles.zip -d /opt/wikitest_files/

if [ -e /var/www/socialtext/data/test-data ]; then
    echo "DELETING old test-data workspace"
    sudo -u www-data /usr/bin/st-admin delete-workspace --w test-data  --no-export
fi
echo "IMPORTING  test-data  WORKSPACE"
sudo -u www-data /usr/bin/st-admin import-workspace --tarball $WIKITESTS/test-data.tar.gz

if [ -e /var/www/socialtext/data/wikitests ]; then
    echo DELETING old wikitests workspace
    sudo -u www-data /usr/bin/st-admin delete-workspace --w wikitests --no-export
fi
echo IMPORTING wikitests WORKSPACE
sudo -u www-data /usr/bin/st-admin import-workspace --tarball $WIKITESTS/wikitests.1.tar.gz

if [ -e /var/www/socialtext/data/calctests ]; then
    echo DELETING old calctests workspace
    sudo -u www-data /usr/bin/st-admin delete-workspace --w calctests --no-export
fi
echo IMPORTING calctests WORKSPACE
sudo -u www-data /usr/bin/st-admin import-workspace --tarball $WIKITESTS/calctests.1.tar.gz

echo GRANTING Accounts and System admin to devnull1
sudo -u www-data /usr/bin/st-admin give-system-admin --e devnull1@socialtext.com
sudo -u www-data /usr/bin/st-admin give-accounts-admin --e devnull1@socialtext.com
echo ""

