#!/bin/bash

BIN="/usr/bin"
DATA="/usr/share/nlw/wikitests"

$BIN/st-config set user_factories 'LDAP:oak-testing;Default' 
cp $DATA/ldap.yaml.st  /etc/socialtext/ldap.yaml
echo " Copied Socialtext ldap.yaml.st  to /etc/socialtext/ldap.yaml"
echo Adding LDAP user devnull3  as test-data workspace admin
$BIN//st-admin add-workspace-admin --u devnull3  --w test-data

echo ""
echo use run-wiki-tests --test-username devnull3  --test-email devnull3@socialtext.com --test-password Ko013344 for LDAP wiki and calc tests
echo or use aliases xlwt and xlct to run test with the devnull3 LDAP user
