#!/bin/bash

BIN="/usr/bin"
DATA="/usr/share/nlw/wikitests"
ETC="/etc/socialtext"
SUDO="sudo -u www-data"

if [ "$1" == "enable" ]; then 
    echo ENABLING LDAP
    sudo $BIN/st-config set user_factories 'LDAP:oak-testing;Default' 
    sudo  cp $DATA/ldap.yaml.st  $ETC/ldap.yaml
    echo " Copied Socialtext ldap.yaml.st  to $ETC/ldap.yaml"
    echo Adding LDAP user devnull3  as test-data workspace admin
    $SUDO $BIN/st-admin add-workspace-admin --u devnull3  --w test-data
    echo ""
    echo use run-wiki-tests --test-username devnull3  --test-email devnull3@socialtext.com --test-password Ko013344 for LDAP wikitests
    echo or use alias xlwt to run test with the devnull3 LDAP user
elif [ "$1" == "disable" ]; then
    echo DISABLING LDAP
    sudo  $BIN/st-config set user_factories 'Default' 
    echo "Removed LDAP from user factories."
    echo Recreating test-data workspace
else
    echo "Usage: st-ldap [enable|disable]"
fi

