#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use Socialtext::Account;
use Socialtext::User;

# Make sure the Socialtext and Unknown accounts exist.
Socialtext::Account->EnsureRequiredDataIsPresent();

# The 2 system users should always be assigned to the Socialtext account
my $st_account = Socialtext::Account->Socialtext;

Socialtext::User->SystemUser->primary_account($st_account);
Socialtext::User->Guest->primary_account($st_account);

exit 0;
