#!/bin/sh
# @COPYRIGHT@

# If socialcalc is installed, run the migration
if [ -d /usr/share/nlw/plugin/socialcalc ]; then
    echo Running migration to move socialcalc file on disk to database
    exit 0
fi

echo Skipping migration because socialcalc is not installed
exit 1
