#!/usr/bin/perl
# @COPYRIGHT@
use warnings;
use strict;

# If socialcalc is installed, run the migration
unless (-d '/usr/share/nlw/plugin/widgets') {
    print "Skipping migration because widgets is not installed\n";
    exit 1;
}

print "Running migration to move widgets to the new db layout";
exit 0;
