#!/usr/bin/perl
#@COPYRIGHT@
use strict;
use warnings;
use Socialtext::Workspace;
use Socialtext::Page::TablePopulator;
use Socialtext::Schema;
use Socialtext::Timer;

my $wksp_timer = Socialtext::Timer->new;
my $total_timer = Socialtext::Timer->new;

my $workspaces = Socialtext::Workspace->All;
my $failures = 0;

# This migration requires that we be running at least version 5 of the
# DBMS schema; the 'page' table _needs_ to be present, see {bz 850} for what
# happens if it is not.
Socialtext::Schema->new->sync( to => 5 );

$total_timer->start_timing(0);
while (my $wksp = $workspaces->next) {
    $wksp_timer->start_timing(0);
    my $name = $wksp->name;
    print "Populating page table with data from $name workspace.\n";
    eval {
        my $populator = Socialtext::Page::TablePopulator->new(
            workspace_name => $name );
        $populator->populate;
    };
    if ($@) {
        $failures++;
        warn $@;
    }
   
    my $elapsed = int($wksp_timer->elapsed*100 + 0.5)/100;
    print "Spent " . $elapsed  . " seconds "
        . " on workspace $name.\n\n";
}

print "TOTAL TIME: " . $total_timer->elapsed . " seconds.\n";

if ($failures) {
    warn "$failures workspaces failed to populate the DB\n";
    exit $failures;
}
exit 0;
