#!/bin/sh
set -e

# These are now *also* run as part of the libsocialtext-reports-perl post-install.
sudo -u postgres st-db sync

# For SocialText Open, there won't be a st-reports-db, so check for existence before we run it.
if which st-reports-db; then
    sudo -u postgres st-reports-db sync
fi
