#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";

use Test::Socialtext::Environment;
use Getopt::Long;
use File::Path;
use Socialtext::Paths;

my %opts;
GetOptions(
    'home:s'   => \$opts{home_dir},
    'help'     => \&show_help,
) or exit 1;

$opts{home_dir} ||= $ENV{HOME};

my $root_dir = $opts{home_dir} . '/.nlw';
my $base_dir = $root_dir . '/root';

if (-e $root_dir) {
    File::Path::rmtree($root_dir);
}

mkdir($root_dir) or die "unable to create $root_dir";

$ENV{NLW_DEV_MODE} = 1;

Test::Socialtext::Environment->CreateEnvironment(
    root_dir       => $root_dir,
    base_dir       => $base_dir,
    fixtures       => ['ALL'],
    ports_start_at => 20000,
    verbose        => 1,
);

my $backup_dir = Socialtext::Paths::storage_directory("db-backups");
File::Path::mkpath($backup_dir) or die "Unable to create $backup_dir: $!";
die "Didn't create $backup_dir!" unless -d $backup_dir;

exit;


sub show_help {
    print <<'EOF';

 fresh-dev-env [--home <dir>|--help]

 This script accepts the following options:

  --home <dir>  Use <dir> for the install base, not your
                home directory

  --help        Show this text

EOF
    exit;
}
