#!/bin/bash

# Create the calctests workspace, and populate it with content from the branch

PORT=`perl -e 'print $> + 20000'`
SERVER=http://`hostname`:$PORT

echo Creating calctests workspace
calctests=`$ST_CURRENT/nlw/bin/st-admin list-workspaces | grep calctests` || true

if [ "$calctests" == "calctests" ]; then
    echo WARNING: $calctests  already exists
fi
$ST_CURRENT/nlw/bin/st-admin create-workspace --title 'calctests' --name calctests --empty
$ST_CURRENT/nlw/bin/st-admin add-workspace-admin  --email devnull1@socialtext.com --workspace calctests

echo Adding user tester to calctests workspace
$ST_CURRENT/nlw/bin/st-admin  create-user --e tester@ken.socialtext.net --p wikitest
$ST_CURRENT/nlw/bin/st-admin add-member  --e tester@ken.socialtext.net --w calctests

echo Server is $SERVER

DIR=$ST_CURRENT/nlw/share/workspaces/calctests
stu-local-copy -s $SERVER -w calctests  -u devnull1@socialtext.com -p d3vnu11l --from $DIR

# get rid of superfluous ceq indexing then index
$ST_CURRENT/nlw/bin/ceq-rm calctests
$ST_CURRENT/nlw/bin/st-admin index-workspace --w calctests --sync

# get rid of superfluous ceq indexing AGAIN
$ST_CURRENT/nlw/bin/ceq-rm calctests

# make a tarball so you don't have to run this script after fdefs
$ST_CURRENT/nlw/bin/st-admin export-workspace --w calctests --dir $ST_CURRENT/nlw/share/workspaces/calctests

echo
echo "calctests are now available at: $SERVER/calctests"
echo Use run-wiki-tests --plan-server $SERVER  --plan-workspace calctests
echo calctests tarball is available at $ST_CURRENT/nlw/share/workspaces/calctests for use after fdefs
echo

