#!/bin/bash -e
# @COPYRIGHT@


USAGE="usage: ./create-clone-workspace /path/to/exported/file.tar.gz [work-space-id [\"Workspace Title\" [DEBUG]]]"
WNAME="default-clone"
WTITLE="Default Cloned Workspace"
DEBUGPRINT=""

if [ !  $1  ]
     then
        echo  $USAGE
        exit 1
fi

if [ -e "$1" ]
    then
        echo MAKING  workspace from tarball: $1
    else
        echo $1 does not exist
        echo $USAGE
        exit 1
fi

if [ "$2" ]
    then
        WNAME=$2
fi

if [ "$3" ]
    then
        WTITLE="$3"
fi

if [ "$4" ]
     then
        DEBUGPRINT="$4"
fi
                
BASENAME=$(basename $1)
SRCNAME=$(basename $1 .tar.gz)

if [ "$USER" == "www-data" ]
    then
        TEMPDIR="/tmp/$WNAME"
        BINDIR="/usr/local/bin"
        DEVBINDIR=""
        ROOTDIR="/var/www/socialtext"
    else
        TEMPDIR=$(dirname $0)/../dev-tmp
        BINDIR=$(dirname $0)/../bin
        DEVBINDIR=$(dirname $0)/../dev-bin
        ROOTDIR=$HOME/.nlw/root
fi

DEVDIR=$TEMPDIR/$WNAME
DATADIR=$ROOTDIR/data
                                                                                
if [ "$DEBUGPRINT" ]
    then
        echo BASENAME IS $BASENAME
        echo SRCNAME IS $SRCNAME
        echo TEMPDIR IS $TEMPDIR
        echo BINDIR IS $BINDIR
        echo DEVBINDIR IS $DEVBINDIR
        echo DEVDIR IS $DEVDIR
        echo ROOTDIR IS $ROOTDIR
        echo DATADIR IS $DATADIR
        echo WNAME IS $WNAME
        echo WTITLE IS "$WTITLE"
fi

if [ -e $TEMPDIR ]; then
    echo REMOVING old temp directories
    rm -rf $TEMPDIR
fi

if [ $DEBUGPRINT ]
    then
        echo MAKING temp directories
fi

mkdir $TEMPDIR
mkdir $DEVDIR

echo COPYING $1 to $DEVDIR
cp  $1 $DEVDIR


pushd $DEVDIR > /dev/null
echo EXTRACTING  $BASENAME
/bin/tar -zxf  $BASENAME
popd > /dev/null

if [ "$DEVBINDIR" ]
    then
        echo STOPPING SERVERS
        $DEVBINDIR/nlwctl stop
fi

if [ -e $DATADIR/$WNAME ]
    then
        echo WORKSPACE $WNAME already exists
    else
        echo CREATING WORKSPACE $WNAME with title "$WTITLE" 
        $BINDIR/st-create-workspace $WNAME "$WTITLE"
       # echo CREATED $WNAME  workspace
        $BINDIR/st-admin add-member --workspace $WNAME --email devnull1@socialtext.com
        $BINDIR/st-admin add-workspace-admin --workspace $WNAME --email devnull1@socialtext.com
fi

echo COPYING plugin data
PLUGINFROM=$DEVDIR/plugin
PLUGINTO=$ROOTDIR/plugin

if [ "$DEBUGPRINT" ]
     then
        echo ABOUT TO REMOVE $PLUGINTO/$WNAME
        echo ABOUT TO COPY FROM $PLUGINFROM/$SRCNAME/ TO $PLUGINTO/$WNAME
fi

rm -rf $PLUGINTO/$WNAME/
cp -rp $PLUGINFROM/$SRCNAME/ $PLUGINTO/$WNAME/

echo COPYING page data
DATAFROM=$DEVDIR/data
DATATO=$ROOTDIR/data

if [ "$DEBUGPRINT" ]
    then
        echo ABOUT TO REMOVE $DATATO/$WNAME
        echo ABOUT TO COPY FROM $DATAFROM/$SRCNAME TO $DATATO/$WNAME
fi
        
rm -rf $DATATO/$WNAME/
cp -rp $DATAFROM/$SRCNAME/ $DATATO/$WNAME/

if [ "$DEVBINDIR" ]
    then
        echo RESTARTING SERVERS
        $DEVBINDIR/nlwctl start
fi

if [ "$DEBUGPRINT" ]
    then
        echo KEEPING temp directories at $TEMPDIR
    else
        echo REMOVING temp directories
        rm -rf $TEMPDIR
fi

echo REINDEXING $WNAME  COULD TAKE MANY MINUTES
$BINDIR/st-admin delete-search-index --workspace $WNAME
$BINDIR/st-admin index-workspace --workspace $WNAME

echo DONE
