#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Socialtext::Resting::RegressionTest;
use JSON;

my $filename = shift || 'test-data.tar.gz';

my $rester = Socialtext::Resting::RegressionTest->new;

$rester->accept('application/json');
my $attachments = jsonToObj( $rester->get_page_attachments('Test data') );

for my $a (@$attachments) {
    warn $a->{name};
    next if $a->{name} ne 'test-data.1.tar.gz';

    (my $attachment_id = $a->{uri}) =~ s#.+/attachments/([^/]+)/.+#$1#;
    print "fetching $attachment_id\n";
    my $tarball = $rester->get_attachment($attachment_id);
    print "Saving to $filename\n";
    open(my $fh, ">$filename") or die "Can't open $filename: $!";
    binmode $fh;
    print $fh $tarball;
    close $fh or die "Can't write $filename: $!";
    exit;
}

die "Couldn't find the test data tarball!\n";
