#!/bin/bash -e
# @COPYRIGHT@

if [ "$ST_CURRENT" != "" ]; then
    echo "Changing to $ST_CURRENT/nlw"
    cd $ST_CURRENT/nlw
fi

perl -MCwd -le'print "Running ", Cwd::abs_path(shift)' $0

START_PORT=21000 # for SSL

function rm_dir {
   DIR=`bin/st-config echo $1`
   if [ -d $DIR ]; then rm -r $DIR; fi
}

if [ "$1" = "--single" ]; then
    FDEFS_PROXY=0
else
    FDEFS_PROXY=1
fi

cd $(dirname $0)/..

./dev-bin/create-skinlinks

set -x
PORT=$(($START_PORT+$UID)) ./configure --dev=1 --apache-proxy=$FDEFS_PROXY --server-admin=support@socialtext.com
set +x

# Remove a bunch of stuff
if [ -e t/tmp ]; then
    dev-bin/nlwctl --test stop
    rm -r t/tmp* &
fi
rm_dir "template_compile_dir";
rm_dir "formatter_cache_dir";

# Shut down any running copy of ST and/or OpenLDAP
set -x
NLWCTL_QUIET=1 dev-bin/nlwctl stop
if [ -e ~/.nlw ]; then
    dev-bin/st-bootstrap-openldap stop
fi
dev-bin/_fresh-dev-env

# Setup robots.txt file to prevent dev-env heat death
perl -le 'print "User-agent: *\nDisallow: /"' > ~/.nlw/root/docroot/robots.txt

echo "Linking in extra modules ..."
# We set +e here so that if these fail, fdefs continues
# otherwise everyone is forced to have all this code checked out
set +e
dev-bin/link-control-panel
dev-bin/link-console
dev-bin/link-reports
dev-bin/link-plugins widgets agile csskit dashboard people signals socialcalc apache
set -e

(cd ../plugins; make clean all);

export PGUSER=`st-config echo db_user`
echo "Adding special dev-env SQL hacks"
psql -f etc/socialtext/db/dev.sql

if [ $FDEFS_PROXY = 0 ]; then
    echo "Starting in single-Apache mode";
    dev-bin/gen-config --root=$HOME/.nlw --apache-proxy=$FDEFS_PROXY --socialtext-open=0;
    dev-bin/nlwctl -c start;
    dev-bin/nlwctl -1 start;
else
    echo "Starting in dual-Apache mode";
    dev-bin/nlwctl start;
fi

st-admin set-workspace-config --workspace admin skin_name s3
