#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use File::Path qw/mkpath/;
use FindBin;

my $branch_arg = shift;
my $branch = $branch_arg;

if ($branch) {
    $branch = "branches/$branch";
}
else {
    my $current_branch = qx(current-branch);
    chomp $current_branch;
    $branch = "branches/$current_branch";
}

print "Linking in control panel from $branch...\n\n";
my $control_base = "$ENV{HOME}/src/st/control";
my $control_dir = "$control_base/$branch";

if (!-d $control_dir && -d "$control_base/.git") {
    $control_dir = $control_base
}

# Look for a symlink to the control panel area beside nlw/
my $possible_dir = "$FindBin::Bin/../../control";
if (!$branch_arg and -d $possible_dir) {
    $control_dir = $possible_dir;
}
else {
    die "Control is not checked out to $control_base" unless -d $control_base;
}

unless (-d $control_dir) {
    warn "Couldn't find control branch '$control_dir' - using trunk";
    $control_dir = "$control_base/trunk";
    die "Couldn't find control trunk '$control_dir'" unless -d $control_dir;
}

my @libs = qw(
    lib/Socialtext/AccessHandler/IsBusinessAdmin.pm
    lib/Socialtext/Handler/ControlPanel.pm
);

for my $f (@libs) {
    print "Linking in $f...\n";
    (my $dir = $f) =~ s#^(.+)/.+#$1#;
    unless (-d $dir) {
        mkpath $dir or die "Can't mkpath $dir: $!";
    }
    unlink $f;
    symlink "$control_dir/$f", $f or die "Can't symlink $control_dir/$f, $f: $!";
}

print "Linking in control templates...\n";
my $tmpl_dir = "share/template/control";
unlink $tmpl_dir;
symlink "$control_dir/$tmpl_dir", $tmpl_dir
    or die "Can't symlink $control_dir/$tmpl_dir => $tmpl_dir: $!";
