#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Test::Socialtext;
use Socialtext::User;
use Getopt::Long;
use Time::HiRes qw/tv_interval gettimeofday/;

$| = 1;
srand(time);

my $hub = new_hub('admin');
my $page;
my $pages = 5000;
my $tags  = 100;
my $tags_per_page = 3;
GetOptions(
    'pages=s' => \$pages,
    'tags=s'  => \$tags,
    'tags-per-page=s' => \$tags_per_page,
) or usage();


my $overall_start = [gettimeofday];
for ( 1 .. $pages ) {
    my $tags = random_tags();
    print "Creating Page $_ with " . scalar(@$tags) . " tags ... ";
    my $start = [gettimeofday];
    $page = Socialtext::Page->new( hub => $hub )->create(
        title   => "Page $_",
        content => 'First Paragraph',
        creator => Socialtext::User->SystemUser,
        categories => random_tags(),
    );
    print tv_interval($start), "\n";
}
print "Created $pages pages in " . tv_interval($overall_start) . "ms\n";

exit;

sub random_tags {
    my $min = 0;
    my $max = $tags_per_page * 2;
    my $num = $min + rand($max - $min);
    return [] unless $num > 0;
    return [ map { "tag $_" } 1 .. $num ];
}


sub usage {
    die <<EOT;
USAGE: $0 [--pages=30] [--tags=8] [--tags-per-page=3]

Creates a bunch of pages.

tags per page is a weighted average.
EOT
}
