#!/usr/bin/env perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../../socialtext-reports/lib";
use Socialtext::Reports::DB qw/connect_params get_dbh/;
use Socialtext::Workspace;
use Socialtext::User;
use Socialtext::Role;
use Time::localtime;

my $dbh = get_dbh();

#---Globals
my $member = Socialtext::Role->Member();
my $iMonth = 0;  #closure
#--------
require Socialtext::Account;
my $name = 'test_stub_account';
my @aWorkspaces = ('a_test_stub_ws','b_test_stub_ws');
my ($account, $account_id) = get_account($name);
my @wsObjects = create_workspaces($account, \@aWorkspaces, $account_id);
my @users = ('t_stub01@socialtext.com','t_stub02@socialtext.com','t_stub03@socialtext.com','t_stub04@socialtext.com',
             't_stub05@socialtext.com', 't_stub06@socialtext.com');
my $userObjs = create_users(\@users, \@wsObjects);
my $tm = localtime;
my $stamp = $tm->year . "-" . $tm->mon . "-" . $tm->mday . "-" . $tm->hour . "-" . $tm->min . "-" . $tm->sec;
my $nlw = "test_nlw.log"; 

#----------------------------------------------------------#
#  Create the Files and setup for import
print_nlw_log(\@wsObjects, $userObjs, $nlw);
my $access = "test_access.log";
#Now we are going to delete a workspace and a user
#$wsObjects[1]->delete;
#$wsObjects[0]->remove_user(user => $userObjs->[1]);
print_access_log(\@wsObjects, $userObjs, $access);

#my $str = 'psql -U nlw NLW_reports -c "delete from actions_by_user where account_id =' . $account_id . '; "';
#`$str`; 
#$str = 'psql -U nlw NLW_reports -c "delete from nlw_log_actions where account_id =' . $account_id . '; "';
#`$str`;
#----------------------------------------------------------#


#---END MAIN ROUTINE SUBROUTINES FOLLOW

sub get_account {
   my $accountname = shift;
   my $account; 
   my $id;

   if ($account = Socialtext::Account->new( name => $name ) ) {
        print "$name account is allready present. \n";
    }
    else {
        $account = eval { Socialtext::Account->create( name => $name ) };

        if ( my $e = Exception::Class->caught('Socialtext::Exception::DataValidation') ) {
             my $msg  = "The following errors occurred when creating the new account:\n\n";
             for my $m ( $e->messages ) {
                 $msg .= "  * $m\n";
             }
             print "ERROR -  $msg\n";
         }
         elsif ( $e = $@ ) {
              die $e;
         }
   }

   $id = $account->account_id();
   print "Account ID: $id\n";
   return ($account, $id);
}


sub create_workspaces {
    my @wsObjs;
    my ($account, $workspaces, $account_id) = @_;
    foreach my $workspace (@$workspaces) {
        print "Looping in $workspace\n";
        my $ws;
        eval {
            $ws = Socialtext::Workspace->new(name => $workspace);
            if (Socialtext::Workspace->NameIsValid( name => $workspace ) ) {
                print "Creating Workspace $workspace ...\n";
                $ws = Socialtext::Workspace->create(name       => $workspace,
                                                    title      => $workspace,
                                                    account_id => $account_id);
                print "Created workspace $workspace \n";
                push @wsObjs, $ws;
                print "Ref to workspace is " . ref($ws) . "\n";
            } else {
               print "Name $workspace is not valid\n";
            }
        };

        if (defined($ws)) { 
            push @wsObjs, $ws;
            print "pushing object" . ref($ws) . "\n";
        }
    } 
    return @wsObjs;
}


sub create_users {
    my ($rausers, $raworkspaces) = @_;
    my @arrUserObjs;

    my $first_ws = 1;
    foreach my $ws (@$raworkspaces) {
        foreach my $username (@$rausers) {
            my $user = Socialtext::User->new(username=> $username);
            if ($user && $first_ws) {
                push @arrUserObjs, $user;
            }
            else {
                eval {
                    $user = Socialtext::User->create(username=> $username,
                                                     email_address => $username,
                                                     password=> 'password');
                     };
                next if $@;
                if ($first_ws) { push @arrUserObjs, $user; }
            }
            unless (  $ws->has_user( $user ) ) {
                $ws->add_user(user => $user,
                              role => $member); 
            }
        }
        $first_ws = 0;
    }
   return (\@arrUserObjs);
}


sub print_nlw_log {
    #Add all users to workspaces
    my @dates = ('Dec 30 2007','Dec 11 2007','Jan 10 2008','Jan 11 2008','Jan 12 2008', 'Jan 13 2008', 'Feb 1 2008');
    my $date_count = 0;
    my ($raWorkspaces, $rausers, $nlw) = @_;
    my $page = 'a';

    #Open The File
    open NLWFILE, "> $nlw" or die "Can't open $nlw : $!";
   
    #Print Create Workspace for Each Workspace
    foreach my $workspace (@$raWorkspaces) {
        print "Creating workspace entry " . $workspace->name . "\n";
        my $str = create_workspace_nlw_entry($workspace);
        print NLWFILE $str;
        foreach my $user (@$rausers) {
          my $str = create_user_nlw_entry($user, $workspace);
            print NLWFILE $str;
            if (defined($dates[$date_count])) {
                $str = create_page_nlw_entry($user, $workspace, $dates[$date_count], $page);
                print NLWFILE $str;
                $page++;
                $date_count++;
            }
        }
        
    }

    my $add_delete = create_and_delete_thirty_pages($rausers, $raWorkspaces);

 
    print NLWFILE $add_delete;

#my $str = 'Feb 28 08:41:09 www nlw[7146]: [33] DELETE,WORKSPACE,workspace:b_test_stub_ws(32787),[1.029888]';
    #$str.= "\n". 'Feb 28 08:41:09 www nlw[7146]: [33] DELETE,USER,user:t_stub02@socialtext.com(32787),[1.029888]' . "\n"; 
    #print NLWFILE $str;
    #Close The File
    close NLWFILE;
}

sub create_and_delete_thirty_pages {
   my ($rausers, $raWorkspaces) = @_;
    my $idx;
    my $add_delete = '';
    for ($idx=1;$idx<31;$idx++) {
        #Add a page and delete it
        my $month = 'Mar';
        my $page = 'blue' . $idx;
        $add_delete .= create_page_nlw_entry($rausers->[0], $raWorkspaces->[-0], $month.' 1 2008',$page);   
        $add_delete .= $month .  ' 2 2008 13:03:08 qa2 nlw[21556]: [33] ACTION,EDIT_CONTENT,page_name:'.$page.',WORKSPACE:'.
                                 $raWorkspaces->[0]->workspace_id . ',USER:'.$rausers->[0]->user_id . ',PAGE:'  
                                 . $raWorkspaces->[0]->name . ',[drop_workspace_breadcrumb:0.003885,overall:0.021291]' . "\n";

        $add_delete .= $month . ' 2 2008 13:03:23 qa2 nlw[21558]: [33] ACTION,DISPLAY,page_name:'.$page.',WORKSPACE:' .
                                  $raWorkspaces->[0]->workspace_id . ',USER:'.$rausers->[0]->user_id .
                                  ',PAGE:blue,[drop_workspace_breadcrumb:0.002642,overall:0.243288]' . "\n";
 
        $add_delete .= $month . ' 2 2008 13:07:05 qa2 nlw[21563]: [33] DELETE,PAGE,workspace:' . $raWorkspaces->[0]->name . '(' .
                                   $raWorkspaces->[0]->workspace_id . ')' .
                                 ',page:blue,user:'. $rausers->[0]->email_address . 
                                 '(' . $rausers->[0]->user_id . '),[NA]' . "\n";
  
         $add_delete .= $month . ' 2 2008 13:07:05 qa2 nlw[21563]: [33] ACTION,DELETE_PAGE,page_name:'.$page.',WORKSPACE:'
                                  . $raWorkspaces->[0]->workspace_id . ',USER:'.$rausers->[0]->user_id . 
                                  'PAGE:blue,[drop_workspace_breadcrumb:0.005555,overall:0.143584]' . "\n";
    }
    return $add_delete;
}

sub print_access_log {
    my ($wsObjects, $userObjs, $filename) = @_;
    my $accessfile;
    open $accessfile, "> $filename" or die "Can't open $filename : !";
    #Each User Reads once from the first WS, Twice from the second
    #The first two users edit pages
    #Everyone vies
    my @arrBelongs;
    $arrBelongs[0] = { 'user' => $userObjs->[0],'pages' => ['a','b','c','d'], 'alt-pages'=>['ab','ba','ca'], function=>'both'};
    $arrBelongs[1] = { 'user' => $userObjs->[1],'pages' => ['a','b','c'], 'alt-pages'=>['ab','ba'], function=>'viewer'};
    
    Process_Access_Log($wsObjects, '30/Dec/2007', \@arrBelongs, $accessfile);
    $arrBelongs[2] = { 'user' => $userObjs->[2],'pages' => ['a','b','c','d'], 'alt-pages'=>['ab','ba','ca'], function=>'viewer', 'comments'=>['b','d']};
    $arrBelongs[3] = { 'user' => $userObjs->[3],'pages' => ['a','c'], 'alt-pages'=>['ab','ca'], function=>'viewer'};
        
    Process_Access_Log($wsObjects, '30/Jan/2008', \@arrBelongs, $accessfile);
    $arrBelongs[4] = { 'user' => $userObjs->[4],'pages' => ['d','e','f','a'], 'alt-pages'=>['da','ea','fa'], function=>'both'};
    $arrBelongs[3] = { 'user' => $userObjs->[3],'pages' => ['a','c','d'], 'alt-pages'=>['ab','ca','da'], function=>'viewer'};
    $arrBelongs[5] = { 'user' => $userObjs->[5],'pages' => ['a','b','f'], 'alt-pages'=>['ab','ba','fa'], function=>'viewer', 'alt-comments'=>['ef']};
    Process_Access_Log($wsObjects, '28/Feb/2008', \@arrBelongs, $accessfile);
            
    Process_Access_Log($wsObjects, '19/Mar/2008', \@arrBelongs, $accessfile);
    #Double Up In March For good measure
    Process_Access_Log($wsObjects, '20/Mar/2008', \@arrBelongs, $accessfile);
       
    my $str=<<EOQ;
127.0.0.1 - - [01/Mar/2008:13:33:33 -0700] "GET /nlw/submit/logout HTTP/1.1" 302 286 "http://qa2.socialtext.net:22015/a_test_stub_ws/`/index.cgi?announcements_and_links" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 3
127.0.0.1 - - [01/Mar/2008:13:33:35 -0700] "GET /nlw/login.html HTTP/1.1" 200 3145 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?announcements_and_links" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 1
127.0.0.1 - - [01/Mar/2008:13:33:42 -0700] "POST /nlw/submit/login HTTP/1.1" 302 277 "http://qa2.socialtext.net:22015/nlw/login.html" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 3
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:33:47 -0700] "GET /a_test_stub_ws/index.cgi HTTP/1.1" 200 25055 "http://qa2.socialtext.net:22015/nlw/login.html" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 5
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:03 -0700] "GET /a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage HTTP/1.1" 200 45563 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 2
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:07 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links?verbose=1;link_dictionary=s2;iecacheworkaround=13:34:11 HTTP/1.1" 200 2119 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25473 2
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:16 -0700] "POST /data/workspaces/a_test_stub_ws/pages/announcements_and_links/tags/yo HTTP/1.1" 201 5 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 26266 1
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:18 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links/tags?iecacheworkaround=13:34:23 HTTP/1.1" 200 58 "http://qa2.socialtext.net:22015/atest_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 1
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:22 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links?verbose=1;link_dictionary=s2;iecacheworkaround=13:34:23 HTTP/1.1" 200 2127 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25473 5
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:31 -0700] "POST /data/workspaces/a_test_stub_ws/pages/announcements_and_links/tags/yadda HTTP/1.1" 201 5 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 7481 4
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:32 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links/tags?iecacheworkaround=13:34:37 HTTP/1.1" 200 109 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 1
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:34:35 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links?verbose=1;link_dictionary=s2;iecacheworkaround=13:34:37 HTTP/1.1" 200 2135 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25473 4
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:35:00 -0700] "POST /a_test_stub_ws/index.cgi HTTP/1.1" 200 233 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 26266 4
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:35:04 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links/attachments?iecacheworkaround=13:35:08 HTTP/1.1" 200 328 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 26266 2
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:35:06 -0700] "GET /data/workspaces/a_test_stub_ws/pages/announcements_and_links?verbose=1;link_dictionary=s2;iecacheworkaround=13:35:10 HTTP/1.1" 200 2340 "http://qa2.socialtext.net:22015/a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25472 2
127.0.0.1 - t_stub01\@socialtext.com [25/Mar/2008:13:35:13 -0700] "GET /a_test_stub_ws/index.cgi?action=display;page_name=Announcements%20and%20Links;js=show_edit_div;caller_action=homepage HTTP/1.1" 200 47455 "-" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 26266 4
EOQ

my $str2 =<<EOQ;
127.0.0.1 - t_stub01\@socialtext.com [08/Mar/2008:14:54:59 +0000] "GET /a_test_stub_ws/index.cgi?action=page_info;page_name=blue%206 HTTP/1.1" 200 1142 "http://qa2.socialtext.net/test-data/index.cgi?action=display;page_name=Untitled%20Page" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13" 21569 0
127.0.0.1 - t_stub01\@socialtext.com [08/Mar/2008:14:55:00 +0000] "POST /a_test_stub_ws/index.cgi HTTP/1.1" 302 5 "http://qa2.socialtext.net/test-data/index.cgi?action=display;page_name=Untitled%20Page" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13" 21570 0
127.0.0.1 - t_stub01\@socialtext.com [08/Mar/2008:14:55:00 +0000] "GET /a_test_stub_ws/index.cgi?blue HTTP/1.1" 200 33410 "http://qa2.socialtext.net/test-data/index.cgi?action=display;page_name=Untitled%20Page" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13" 21569 0
EOQ

#127.0.0.1 - t_stub01\@socialtext.com [08/Apr/2008:14:55:11 +0000] "GET /a_test_stub_ws/index.cgi?action=delete_page;page_name=blue HTTP/1.1" 302 5 "http://qa2.socialtext.net/test-data/index.cgi?blue" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13" 21570 0
#127.0.0.1 - t_stub01\@socialtext.com [08/Apr/2008:14:55:11 +0000] "GET /a_test_stub_ws/index.cgi?action=delete_epilogue&page_id=blue HTTP/1.1" 200 6617 "http://qa2.socialtext.net/test-data/index.cgi?blue" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13" 21569 0
#EOQ

      $str=~s/\n$//g;
      $str2=~s/\n$//g;
      #my $date = get_current_month(); 
      #my $fulldate = '01/' . $date . '/';
      #$str=~s/25\/Mar\//$fulldate/g;
     
#
    print $accessfile $str;
    print $accessfile $str2;
    close $accessfile;
}

sub get_current_month {
  my $date = gmtime;
  $date = substr($date,4,3);
  return $date;
}

sub Process_Access_Log {
    my ($wsObjects, $date, $arrBelongs, $accessfile) = @_;
   
    my $ws_num = 1;
    foreach my $ws (@$wsObjects) {
         my $comments = 'comments';
         my $key = 'pages';
         if ($ws_num==2) {
             $key = 'alt-pages';
             $comments = 'alt-comments';
         } 
         foreach my $user (@$arrBelongs) {
            my $ra = $user->{$key};
            my $email = $user->{'user'}->email_address;
            foreach my $page (@$ra) {
                if ($user->{'function'} eq 'both') {
                    #Add edit notices 
                    my $str = '127.0.0.1 - ' .$email . ' [' . $date . ':10:00:09 -0700] "POST /'. $ws->name 
                              . '/index.cgi HTTP/1.1" 200 28428 "http://www.socialtext.net/' . $ws->name . '/index.cgi?' 
                              . $page . '" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 18115 1' . "\n";
                    
                    print $accessfile $str;
                }
                
                #Plus Two Views of Said Page
                my $str = '127.0.0.1 - ' .$email . ' [' . $date . ':10:00:09 -0700] "GET /' . $ws->name
                          . '/index.cgi/' . $page . ' HTTP/1.1" 200 28428 "http://www.socialtext.net/' . $ws->name . '/index.cgi?'
                          . $page . '" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 18115 1' . "\n";
                                                                                           
                print $accessfile $str; print $accessfile $str;
            }
            
            if (defined($user->{$comments})) {
                my $ra = $user->{$comments};
                foreach my $page (@$ra) {
                    my $email = $user->{'user'}->email_address;
                    my $str = '127.0.0.1 - ' . $email .' [' . $date . ':10:10:09 -0700] "POST /' . $ws->name
                          . '/index.cgi HTTP/1.1" 200 359 "http://qa2.socialtext.net/' . $ws->name . '/index.cgi?action=enter_comment;page_name=' 
                          . $page . ';caller_action=display" "Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.12) Gecko/20080201 Firefox/2.0.0.12" 25473 1' . "\n";
                    print $accessfile $str;
                }
            }                
        }   
        $ws_num++;
    }   
}


sub create_workspace_nlw_entry {
    my ($ws) = @_;
    my $str = "Dec 01 2007 13:20:15 talc nlw[30088]: [2013] CREATE,WORKSPACE,workspace:" . $ws->name . '(' . $ws->workspace_id . '),[0.449366]' . "\n";
    return $str;

}


sub create_page_nlw_entry {
    my ($user, $ws, $date, $page) = @_;
   my $user_id = $user->user_id;

    my $str = "$date 13:57:00 qa2 nlw[7636]: [33] CREATE,PAGE,workspace:";
    $str.=$ws->name . '(' . $ws->workspace_id . ')';
    $str.=',page:'.$page .',user:' . $user->email_address . '(' . $user_id . '),[0.035587]' . "\n"; 
    $str.="$date 13:57:00 qa2 nlw[7635]: [33] DISPLAY_PAGE,workspace:" . $ws->name . '(' . $ws->workspace_id . ')' . ',page:'.$page .',user:' . $user->email_address . '(' . $user_id .  '),[0.035587]' . "\n";
    return $str;
}


sub create_user_nlw_entry {
   my ($user, $ws) = @_;
   my $email = $user->email_address;
   my $user_id = $user->user_id;
   my @monthArr = ('Dec 01 2007','Dec 01 2007','Jan 01 2008','Jan 01 2008','Feb 01 2008','Feb 01 2008');
   my $month = $monthArr[$iMonth];
   my $str = $month . " 12:00:00 talc nlw[30088]: [2013] ASSIGN,USER_ROLE,role:member,user:$email" .
             '(' . $user_id . ')' . ",workspace:" . $ws->name .'('.$ws->workspace_id.'),[0.001709]'."\n";
   
   $iMonth++;
   if ($iMonth>5) { $iMonth=5; }
   return $str;
}


