#!/bin/bash

$ST_CURRENT/nlw/bin/st-config set user_factories 'LDAP:oak-testing;Default' 
cp $ST_CURRENT/nlw/dev-bin/ldap.yaml.st  $HOME/.nlw/etc/socialtext/ldap.yaml
echo " Copied Socialtext ldap.yaml.st  to $HOME/.nlw/etc/socialtext/ldap.yaml"
echo Creating test-data workspace
$ST_CURRENT/nlw/dev-bin/create-test-data-workspace
echo Adding LDAP user devnull3  as test-data workspace admin
$ST_CURRENT/nlw/bin/st-admin add-workspace-admin --u devnull3  --w test-data
$ST_CURRENT/nlw/dev-bin/nlwctl restart
echo ""
echo use run-wiki-tests --test-username devnull3  --test-email devnull3@socialtext.com --test-password Ko013344 for LDAP wiki and calc tests
echo or use aliases xlwt and xlct to run test with the devnull3 LDAP user
