#!/bin/bash

BIN="$ST_CURRENT/nlw/bin"
DEVBIN="$ST_CURRENT/nlw/dev-bin"
ETC="$HOME/.nlw/etc/socialtext"

if [ "$1" == "enable" ]; then 
    echo ENABLING LDAP
    $BIN/st-config set user_factories 'LDAP:oak-testing;Default' 
    cp $DEVBIN/ldap.yaml.st  $ETC/ldap.yaml
    echo " Copied Socialtext ldap.yaml.st  to $ETC/ldap.yaml"
    echo Creating test-data workspace
    $DEVBIN/create-test-data-workspace
    echo Adding LDAP user devnull3  as test-data workspace admin
    $BIN/st-admin add-workspace-admin --u devnull3  --w test-data
# removed apache restart.  Should not be needed.
    echo ""
    echo use run-wiki-tests --test-username devnull3  --test-email devnull3@socialtext.com --test-password Ko013344 for LDAP wiki and calc tests
    echo or use aliases xlwt and xlct to run test with the devnull3 LDAP user
elif [ "$1" == "disable" ]; then
    echo DISABLING LDAP
    $BIN/st-config set user_factories 'Default' 
    echo "Removed LDAP from user factories."
    echo Recreating test-data workspace
    $DEVBIN/create-test-data-workspace
# removed apache restart.  Should not be needed.
else
    echo "Usage: st-ldap [enable|disable]"
fi

