#!/usr/bin/perl
# @COPYRIGHT@
use strict;
use warnings;
use FindBin;
use lib "$FindBin::Bin/../lib";
use Socialtext::Schema;
use Socialtext::System qw/shell_run/;

my $nlw_base = "$FindBin::Bin/..";
my $schema = Socialtext::Schema->new;
my $schema_file = $schema->_schema_filename;
$schema_file =~ s#.+/(etc/socialtext.+)#$1#;
my $schema_name = $schema->schema_name;

# Get a virgin base schema
shell_run("scm revert $nlw_base/$schema_file");
copy_schema_files_to_dev_env();

# Set up the fresh schema from socialtext-schema.sql
shell_run("nlwctl -1 stop");
shell_run("st-db recreate --force --schema socialtext");

# Sync to the latest version (what you just wrote - X-to-Y.sql)
shell_run("st-db sync --schema socialtext ");

shell_run("$FindBin::Bin/dump-schema");

copy_schema_files_to_dev_env();
exit;

sub copy_schema_files_to_dev_env {
    shell_run("cp $nlw_base/etc/socialtext/db/* ~/.nlw/etc/socialtext/db");
}
